
package com.nsu.flightapp.model;

import javax.xml.namespace.QName;
import jakarta.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FlightServiceSOAP", targetNamespace = "http://soap.nsu.com/flights", wsdlLocation = "https://flight-soap-service-e6gvashufkh8cuhj.eastus-01.azurewebsites.net/FlightEndpointImpl?wsdl")
public class FlightServiceSOAP
    extends Service
{

    private final static URL FLIGHTSERVICESOAP_WSDL_LOCATION;
    private final static WebServiceException FLIGHTSERVICESOAP_EXCEPTION;
    private final static QName FLIGHTSERVICESOAP_QNAME = new QName("http://soap.nsu.com/flights", "FlightServiceSOAP");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = URI.create("https://flight-soap-service-e6gvashufkh8cuhj.eastus-01.azurewebsites.net/FlightEndpointImpl?wsdl").toURL();
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FLIGHTSERVICESOAP_WSDL_LOCATION = url;
        FLIGHTSERVICESOAP_EXCEPTION = e;
    }

    public FlightServiceSOAP() {
        super(__getWsdlLocation(), FLIGHTSERVICESOAP_QNAME);
    }

    public FlightServiceSOAP(WebServiceFeature... features) {
        super(__getWsdlLocation(), FLIGHTSERVICESOAP_QNAME, features);
    }

    public FlightServiceSOAP(URL wsdlLocation) {
        super(wsdlLocation, FLIGHTSERVICESOAP_QNAME);
    }

    public FlightServiceSOAP(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FLIGHTSERVICESOAP_QNAME, features);
    }

    public FlightServiceSOAP(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FlightServiceSOAP(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FlightEndpoint
     */
    @WebEndpoint(name = "FlightEndpointImplPort")
    public FlightEndpoint getFlightEndpointImplPort() {
        return super.getPort(new QName("http://soap.nsu.com/flights", "FlightEndpointImplPort"), FlightEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlightEndpoint
     */
    @WebEndpoint(name = "FlightEndpointImplPort")
    public FlightEndpoint getFlightEndpointImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.nsu.com/flights", "FlightEndpointImplPort"), FlightEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FLIGHTSERVICESOAP_EXCEPTION!= null) {
            throw FLIGHTSERVICESOAP_EXCEPTION;
        }
        return FLIGHTSERVICESOAP_WSDL_LOCATION;
    }

}
