
package com.nsu.flightapp.model;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FlightEndpoint", targetNamespace = "http://soap.nsu.com/flights")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FlightEndpoint {


    /**
     * 
     * @param id
     * @return
     *     returns com.example.flight.soapclient.Flight
     */
    @WebMethod
    @WebResult(name = "flight", targetNamespace = "")
    @RequestWrapper(localName = "getFlight", targetNamespace = "http://soap.nsu.com/flights", className = "com.example.flight.soapclient.GetFlight")
    @ResponseWrapper(localName = "getFlightResponse", targetNamespace = "http://soap.nsu.com/flights", className = "com.example.flight.soapclient.GetFlightResponse")
    @Action(input = "http://soap.nsu.com/flights/FlightEndpoint/getFlightRequest", output = "http://soap.nsu.com/flights/FlightEndpoint/getFlightResponse")
    public Flight getFlight(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @return
     *     returns java.util.List<com.example.flight.soapclient.Flight>
     */
    @WebMethod
    @WebResult(name = "flights", targetNamespace = "")
    @RequestWrapper(localName = "listFlights", targetNamespace = "http://soap.nsu.com/flights", className = "com.example.flight.soapclient.ListFlights")
    @ResponseWrapper(localName = "listFlightsResponse", targetNamespace = "http://soap.nsu.com/flights", className = "com.example.flight.soapclient.ListFlightsResponse")
    @Action(input = "http://soap.nsu.com/flights/FlightEndpoint/listFlightsRequest", output = "http://soap.nsu.com/flights/FlightEndpoint/listFlightsResponse")
    public List<Flight> listFlights();

    /**
     * 
     * @param flight
     * @return
     *     returns com.example.flight.soapclient.Flight
     */
    @WebMethod
    @WebResult(name = "updatedFlight", targetNamespace = "")
    @RequestWrapper(localName = "updateFlight", targetNamespace = "http://soap.nsu.com/flights", className = "com.example.flight.soapclient.UpdateFlight")
    @ResponseWrapper(localName = "updateFlightResponse", targetNamespace = "http://soap.nsu.com/flights", className = "com.example.flight.soapclient.UpdateFlightResponse")
    @Action(input = "http://soap.nsu.com/flights/FlightEndpoint/updateFlightRequest", output = "http://soap.nsu.com/flights/FlightEndpoint/updateFlightResponse")
    public Flight updateFlight(
        @WebParam(name = "flight", targetNamespace = "")
        Flight flight);

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deleteFlight", targetNamespace = "http://soap.nsu.com/flights", className = "com.example.flight.soapclient.DeleteFlight")
    @ResponseWrapper(localName = "deleteFlightResponse", targetNamespace = "http://soap.nsu.com/flights", className = "com.example.flight.soapclient.DeleteFlightResponse")
    @Action(input = "http://soap.nsu.com/flights/FlightEndpoint/deleteFlightRequest", output = "http://soap.nsu.com/flights/FlightEndpoint/deleteFlightResponse")
    public boolean deleteFlight(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @param flight
     * @return
     *     returns com.example.flight.soapclient.Flight
     */
    @WebMethod
    @WebResult(name = "newFlight", targetNamespace = "")
    @RequestWrapper(localName = "createFlight", targetNamespace = "http://soap.nsu.com/flights", className = "com.example.flight.soapclient.CreateFlight")
    @ResponseWrapper(localName = "createFlightResponse", targetNamespace = "http://soap.nsu.com/flights", className = "com.example.flight.soapclient.CreateFlightResponse")
    @Action(input = "http://soap.nsu.com/flights/FlightEndpoint/createFlightRequest", output = "http://soap.nsu.com/flights/FlightEndpoint/createFlightResponse")
    public Flight createFlight(
        @WebParam(name = "flight", targetNamespace = "")
        Flight flight);

}
